---
title: "Ohio COVID-19 Vaccine Rollout"
author: "IllicitDavid Jackson"
date: "6/19/2021 2:50 PM/EST"
output: 
  html_document: 
    fig_width: 9
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(plotly)
library(RSQLite)
library(dplyr)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))
```

## Ohio COVID Vaccine Rollout
#### Source: John Hopkins Uni.

```{r}
### State Data
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/NYTimes.sqlite3")
df <- dbGetQuery(db,"select * from usvaccine")
df <- df[order(df$Date),]
df <- subset(df,Province_State =="Ohio" )
df$Date <- as.Date(df$Date,format="%Y-%m-%d")
```
```{r}
buckeye <- df %>% select(Date,Doses_admin) %>% na.omit() %>% 
  group_by(Date) %>% summarise(Admin = sum(Doses_admin))
```

### doses_admin_total

```{r}
p0 <- buckeye %>% ggplot() + geom_line(aes(x=Date,y=Admin,fill="red")) +
scale_y_continuous(labels=comma) +
labs(title="doses_admin_total")
ggplotly(p0)
```
```{r}
p1 <- df %>% filter(Vaccine_Type =="All") %>%
  ggplot() + geom_line(aes(x=Date,y=Stage_Two_Doses,col="Stage Two"),lwd=2) +
  geom_line(aes(x=Date,y=Stage_One_Doses,col="Stage Doses"),lwd=2) +
  scale_y_continuous(labels=comma) +
labs(title="Daily Stages One/TWo Doses Covid19 Vaccine")
ggplotly(p1)
```

