---
title:  "Analysis of COVID-19 Data for the  State Of Ohio"
author: "David J Jackson"
date: "Apr. 5, 2010"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=9, fig.height=6)
library(tidyverse)
library(RSQLite)
library(plotly)
```

### Disclaimer:
* This is a personel project, 
* I am not a employee of the state of Ohio. 
* I am not employed in either the medical or data sceince fields.

### Data Source: NY Times
* GitHub: https://github.com/nytimes/covid-19-data.git


```{r, echo=FALSE}
rm(list=ls())
us_states <- data.table::fread("../NYT_covid-19-data/us-states.csv")
us_states$date <-as.Date(us_states$date)
us_total <- us_states %>% group_by(date) %>% 
summarise(Cases=sum(cases), Deaths = sum(deaths),  DeathRate = Deaths/Cases)

us_state_total <- us_states %>% group_by(state,date) %>% 
  summarise(Cases=sum(cases),   Deaths = sum(deaths),                               
   DeathRate = Deaths/Cases)

```
```{r,echo=FALSE}
us_counties <- data.table::fread("../NYT_covid-19-data/us-counties.csv")
us_counties$date <- as.Date(us_counties$date)
us_county_summary <- us_counties %>% group_by(state,county,date) %>% summarise(Cases=sum(cases),Deaths = sum(deaths),DeathRate = Deaths/Cases)

```
```{r,echo=FALSE}
STATESDAILY <-  us_states %>% 
  group_by(date, state) %>%
  summarise(
    TotalCases = sum(cases, na.rm=TRUE),
    TotalDeaths = sum(deaths, na.rm=TRUE)
  ) %>%
  group_by(state) %>%
  arrange(desc(date)) %>%
  mutate(
    PreviousTotalCases = lead(TotalCases),
    PreviousTotalDeaths = lead(TotalDeaths)
  ) %>%
  ungroup() %>%
  na.omit()
STATESDAILY <- STATESDAILY %>% mutate(new_cases = TotalCases - PreviousTotalCases)
STATESDAILY <- STATESDAILY %>% mutate(new_deaths = TotalDeaths - PreviousTotalDeaths)
STATESDAILY <- STATESDAILY %>% mutate(death_rate = new_deaths / new_cases)
STATESDAILY$date <- as.character(STATESDAILY$date)
db <- dbConnect(SQLite(), dbname="../db/CORVID.sqlite3")
dbWriteTable(db, "STATESDAILY",STATESDAILY ,overwrite=TRUE)
```

```{r,echo=FALSE}
COUNTYDAILY <-  us_counties %>% 
  group_by(date,state, county) %>%
  summarise(
    TotalCases = sum(cases, na.rm=TRUE),
    TotalDeaths = sum(deaths, na.rm=TRUE)
  ) %>%
  group_by(state,county) %>%
  arrange(desc(date)) %>%
  mutate(
    PreviousTotalCases = lead(TotalCases),
    PreviousTotalDeaths = lead(TotalDeaths)
  ) %>%
  ungroup() %>%
  na.omit()
COUNTYDAILY <- COUNTYDAILY%>% mutate(new_cases = TotalCases - PreviousTotalCases)
COUNTYDAILY <- COUNTYDAILY%>% mutate(new_deaths = TotalDeaths - PreviousTotalDeaths)
COUNTYDAILY <- COUNTYDAILY%>% mutate(death_rate = new_deaths/new_cases)
COUNTYDAILY$date <- as.character(COUNTYDAILY$date)
dbWriteTable(db, "COUNTYDAILY",COUNTYDAILY,overwrite=TRUE)
```

###  US Totals for Cases,Deaths  by Date


```{r}
STATESDAILY %>% filter(new_cases >0) %>% ggplot() + geom_col(aes(x=date,y=new_cases)) +
      labs(title="US Total Daily Cases by Date") +
     theme(axis.text.x = element_text(angle = 45))

STATESDAILY %>% filter(new_deaths >0)%>% ggplot() + geom_col(aes(x=date,y=new_deaths)) +
      labs(title="US Total Daily Deaths by Date") +
   theme(axis.text.x = element_text(angle = 45))

STATESDAILY %>% filter(new_cases >0) %>% ggplot() + geom_col(aes(x=date,y=death_rate)) +
      labs(title="US Death Rate by Date") +
   theme(axis.text.x = element_text(angle = 45))

```

### Accumulated Daily Totals for Cases,Deaths  by Date

```{r,echo=FALSE}
us_total %>% plot_ly() %>% add_bars(x=~date,y=~Cases) %>%
  layout(title="US Accumulated Daily Cases")

us_total %>% plot_ly() %>% add_bars(x=~date,y=~Deaths) %>%
  layout(title="US Accumulated Daily Deaths")

us_total %>% plot_ly() %>% add_bars(x=~date,y=~DeathRate) %>%
  layout(title="US Daily Rate of Death")
```

### Accumulated  Cases and Deaths by State and Date

```{r,echo=FALSE}
ggplot(us_state_total) + geom_col(aes(x=date,y=Cases,fill=state)) +
  labs(title="Daily Accumulated Cases by Date") +
  theme(axis.text.x = element_text(angle = 90)) + 
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(breaks = "1 week") + theme_gray()



ggplot(us_state_total) + geom_col(aes(x=date,y=Deaths,fill=state)) +
  scale_x_date(breaks = "1 week") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title="Daily Accumulated Deaths by State") +
  scale_y_continuous(labels = scales::comma) + theme_gray()


```

### Accumulated Daily  Deaths and Cases Totals for   Ohio

```{r,echo=FALSE}

ohio_counties <- us_county_summary %>% filter(state=="Ohio")
ggplot(ohio_counties) + geom_col(aes(x=date,y=Cases)) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title="Ohio Daily Accumulated Cases by Date") + theme_gray()


ggplot(ohio_counties) + geom_col(aes(x=date,y=Deaths)) +
  labs(title="OhioAccumulated Deaths by Date") +
  theme(axis.text.x = element_text(angle = 90)) + theme_gray()

```
```{r,echo=FALSE}
ggplot(ohio_counties) + geom_col(aes(x=date,y=Cases,fill=county)) +
  labs(title="Ohio/county Accumulated Cases by Date") +
  theme(axis.text.x = element_text(angle = 90)) + theme_gray()

ggplot(ohio_counties) + geom_col(aes(x=date,y=Deaths,fill=county)) +
  labs(title="Ohio/County Accumulated Deaths by Date") +
  theme(axis.text.x = element_text(angle = 90)) + theme_gray()

```
