---
title: 'Ohio Covid-19 : Can We Trust the Numbers?'
author: "IllicitDavid Jackson"
date: "2/12/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,error=FALSE)
```

# Is The Trend Still Our Firend?
* Can we Trust Ohio's Covid-19 Cases and Deaths
* Ohio health dept. to restructure after 4K unreported deaths(AP)
* https://wpta21.com/2021/02/12/governor-expected-to-discuss-underreported-covid-19-deaths/

```{r}
library(ggplot2)
library(scales)
library(RSQLite)
library(dplyr)
```
```{r}
rm(list=ls())
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/NYTimes.sqlite3")
df <- dbGetQuery(db,"select * from STATESDAILY")
df <- df[order(df$date),]
df$date <- as.Date(df$date)
df <- subset(df,state =="Ohio" & date >="2020-03-10" )

summary(df$new_cases,na.rm=TRUE)
summary(df$new_deaths,na.rm=TRUE)
library(benford.analysis)
library(pracma)  ## Inclused a funcion to do various rolling means calc.
```

# Comparison of Ohio Cases and Deaths

```{r}
df$mac7 <- movavg(df$new_cases,7, type="e")
df$mac14 <- movavg(df$new_cases,28, type="e")
```
```{r}
ggplot(df) + geom_line(aes(x=date,y=mac7)) +
  labs(title="Ohio Cases: 7 Day Moving Average")
```
```{r}
ggplot(df) + geom_line(aes(x=date,y=mac14)) +
  labs(title="Ohio Cases: 28 Day Moving Average")
```

```{r}
df$mad7 <- movavg(df$new_deaths,7, type="e")
df$mad28 <- movavg(df$new_deaths,28, type="e")

ggplot(df) + geom_line(aes(x=date,y=mad7)) +
  labs(title="Ohio Deaths: 7 Day Moving Average") +
  ylim(0,90)

ggplot(df) + geom_line(aes(x=date,y=mad28)) +
  labs(title="Ohio Deaths: 28 Day Moving Average") +
  ylim(0,90)

```

# Benford's Analysis: benford.analysis packager
# Daily Cases: First and First Two Digits

```{r}
cases <- df %>% dplyr::select(new_cases)
deaths <- df %>% dplyr::select(new_deaths)

bl_cases <- benford(cases$new_cases,1)
plot(bl_cases,multiple = FALSE,select="digits")

bl_cases2 <- benford(cases$new_cases,2)
plot(bl_cases2,multiple = FALSE,select="digits")
```

# Daily Deaths: First and First Two Digits

```{r}
bl_deaths <- benford(deaths$new_deaths,1)
plot(bl_deaths,multiple = FALSE,select="digits")
#
bl_deaths2 <- benford(deaths$new_deaths,2)
plot(bl_deaths2,multiple = FALSE,select="digits")
```

