---
title: "Ohio Covid-19 Tweaks"
author: "David Jackson"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(dplyr)
library(dlookr)
library(forecast)
library(flextable)
```

## Adjusted Numbers for Ohio

```{r}
rm(list=ls())
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVID-19-DB/NYTimes.sqlite3")
df <- dbGetQuery(db,"select * from STATESDAILY where state = 'Ohio'")
df$date <- as.Date(df$date)
df <- df[order(df$date),]
```

### Basic Plots: Cases 

```{r}
df %>% ggplot() + geom_line(aes(x=date,y=new_cases)) +
  scale_y_continuous(labels = comma) +
  labs(title="Ohio Daily Cases (raw data)")

df %>% select(new_cases) %>% diagnose_numeric() %>% flextable()
```

### Basic Plots: Deaths

```{r}
df %>% ggplot() + geom_line(aes(x=date,y=new_deaths)) +
  scale_y_continuous(labels = comma) +
  labs(title="Ohio Daily Deaths (raw data)")

df %>% select(new_deaths) %>% diagnose_numeric() %>% flextable()
```

### Loess Plot for Deaths

```{r}
df %>% ggplot() + geom_smooth(aes(x=date,y=new_deaths),span=0.25) +
  scale_y_continuous(labels = comma) +
  labs(title="Ohio Daily Deaths (Loess)",y="Deaths Smoothed")
```

