---
title: "Ohio Weekly COVID-19 Report"
author: "David J Jackson"
date: "7/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RSQLite)
library(lubridate)
```
```{r}
rm(list=ls())
db <- dbConnect(SQLite(), dbname="../COVIDDB/COVID.sqlite3")

us_states <- dbGetQuery(db, "SELECT state,date,cases,deaths FROM us_states;")
us_states$date <-as.Date(us_states$date)
oh_state <- us_states %>% filter(state=="Ohio")  

```
```{r echo=FALSE}

buckeye <- oh_state %>% group_by(date) %>% 
summarise(Cases=sum(cases), Deaths = sum(deaths))   %>%
   mutate(daily_deaths = Deaths - lag(Deaths)) %>% 
   mutate(daily_cases = Cases -  lag(Cases)) %>%
   mutate(DeathRate = daily_deaths/daily_cases)
```

```{r}
GOBUCKS <- buckeye %>% group_by(Weekly = floor_date(date,"week")) %>%
  summarize(Cases = sum(daily_cases),
  Deaths = sum(daily_deaths))
```
```{r}
ggplot(GOBUCKS) + geom_col(aes(x=Weekly,y=Cases)) +
  labs(title="Ohio Weekly Cases")
```
```{r}
ggplot(GOBUCKS) + geom_col(aes(x=Weekly,y=Deaths)) +
  labs(title="Ohio Weekly Deaths")
```

