---
title: "COVID-19: US States(and D.C.) Cases/Deaths"
subtitle: "First 14/30/60 Days"
author: "David J Jackson"
date: "4/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RSQLite)
library(plotly)
knitr::opts_chunk$set(fig.width=9, fig.height=7)
```
```{r, echo=FALSE}
rm(list=ls())
db <- dbConnect(SQLite(), dbname="../COVIDDB/CORVID.sqlite3")

usstates <- dbGetQuery(db, "SELECT state,date,cases,deaths FROM us_states ;")
usstates$date <- as.Date(usstates$date)

states <- usstates %>% filter(state !="American Samoa" &
                       state !="Northern Mariana Islands" &
                      state != "Virgin Islands"  &
                      state != "Puerto Rico" &
                      state != "Guam")
## Get States daily numbers
states_daily <- dbGetQuery(db, "SELECT * FROM STATESDAILY ;")
states_daily$date <- as.Date(states_daily$date)


# Per Joe Harmon on Slack
# states <- usstates %>% !states %in% c("American Samoa", "Northern Mariana Islands",
#                        "Virgin Islands","Puerto Rico","Guam")
```
```{r, echo=FALSE}
# 7 Days
sts <- states %>% filter(date <="2020-01-28" & cases >0 | deaths >0) %>% group_by(state) %>%
      summarise(Cases = sum(cases),Deaths = sum(deaths))
# 14 Days
sts1 <- states %>% filter(date <="2020-02-05" & cases >0 | deaths >0) %>% group_by(state) %>%
      summarise(Cases = sum(cases),Deaths = sum(deaths))
# 30 Days
sts2 <- states %>% filter(date <="2020-02-21" & cases >0 | deaths >0) %>% group_by(state) %>%
      summarise(Cases = sum(cases),Deaths = sum(deaths))
# 60 Days
sts3 <- states %>% filter(date <="2020-03-22" & cases >0| deaths >0) %>% group_by(state) %>%
      summarise(Cases = sum(cases),Deaths = sum(deaths))
```

#### US States Reporting Cases for the First 14/20/60 Days

```{r, echo=FALSE}
ggplot(sts) + geom_col(aes(x=Cases,y=reorder(state,Cases))) + 
  labs(title="US States Reporting Cases",
       subtitle="(During 1st 7 Days: Jan. 22, 2020 -  Jam. 28 ,2020)") 
         
```

```{r, echo=FALSE}
ggplot(sts1) + geom_col(aes(x=Cases,y=reorder(state,Cases))) + 
  labs(title="US States Reporting Cases",
       subtitle="(During 1st 14 Days: Jan. 22, 2020 -  Feb. 05,2020)") 
         
```
```{r, echo=FALSE}
ggplot(sts2) + geom_col(aes(x=Cases,y=reorder(state,Cases))) + 
  labs(title="US States Reporting Cases",
       subtitle="(During 30  Days: Jan. 22, 2020 -  Feb. 21,2020)")
```
```{r,echo=FALSE}
ggplot(sts3) + geom_col(aes(x=Cases,y=reorder(state,Cases))) + 
  labs(title="US States Reporting  Cases",
       subtitle="(During 1st 60 Days: Jan. 22, 2020 -  Mar. 22. 21,2020)") 
```

#### US States Reporting Deaths for the First 14/30/60 Days

```{r, echo=FALSE}
ggplot(sts) + geom_col(aes(x=Deaths,y=reorder(state,Deaths))) + 
  labs(title="US States Reporting Deaths",
       subtitle="(During 1st 7 Days: Jan. 22, 2020 -  Jam. 28,2020)") 
         
```
```{r, echo=FALSE}
ggplot(sts1) + geom_col(aes(x=Deaths,y=reorder(state,Deaths))) + 
  labs(title="US States Reporting Deaths",
       subtitle="(During 1st 14 Days: Jan. 22, 2020 -  Feb. 05,2020)") 
         
```
```{r, echo=FALSE}
ggplot(sts2) + geom_col(aes(x=Deaths,y=reorder(state,Deaths))) + 
  labs(title="US States Reporting Deaths",
       subtitle="(During 30  Days: Jan. 22, 2020 -  Feb. 21,2020)")
```
```{r, echo=FALSE}
ggplot(sts3) + geom_col(aes(x=Deaths,y=reorder(state,Deaths))) + 
  labs(title="US States Reporting  Deaths",
       subtitle="(During 1st 60 Days: Jan. 22, 2020 -  Mar. 22. 21,2020)") 
```
```{r}
usstates <- states %>% mutate(Days = date - as.Date("2020-01-21")) %>%
  group_by(state,date) %>% summarize(
                      first_case = dplyr::first(date)) 
                     # first_death = dplyr::first(deaths))
```
```{r}
usstates <- states %>% mutate(Days = date - as.Date("2020-01-21")) %>%
                  arrange(date) %>%
                  group_by(state) %>%
                  slice(1:1)

```
```{r}
scott <- states %>% mutate(Days = date - as.Date("2020-01-21")) %>%
  arrange(state,date) %>% filter(cases >0) %>%
  group_by(state) %>% filter(row_number()==1)

scott2 <- states %>% mutate(Days = date - as.Date("2019-12-31")) %>%
  arrange(state,date) %>% filter(deaths >0) %>%
  group_by(state) %>% filter(row_number()==1)
                      
```

```{r}
scott  %>%
  ggplot(aes(x=Days,y=state,fill=cases)) +
  geom_tile() + labs(title="First Confirmed Cases by States",
                      x="Days from Jan. 22, 2020",
                      y="US States")

scott  %>%
  ggplot(aes(x=date,y=state,fill=cases)) +
  geom_tile() + labs(title="First Confirmed Cases by States",
                      x="Date of first Cases",
                      y="US States")
```

```{r}
scott2  %>%
  ggplot(aes(x=Days,y=state,fill=cases)) +
  geom_tile() + labs(title="First Reported Cases by States",
                     subtitle="Beginng with first cases in China",
                      x="Days from Dec.  31, 2019",
                      y="US States")
```
